# config.yaml
input_files:
  custom_genes: "datasets/Custom_genes_analysis/custom_genes.txt"
  deg_csv: "datasets/RNAseq/stringtiefile/RNA_GDC_vs_RNA_ctr_DEG.csv"
# === File paths configuration ===
paths:
  dir: "datasets/Custom_genes_analysis"
  scripts_dir: "scripts/snakemake/Custom_genes_analysis/"

  jaspar_dir: "datasets/JASPAR2024_CORE"
  tf_mapping_file: "datasets/Homo_sapiens_TF.txt"

params:
  log2fc_up: 0.2
  log2fc_down: -0.2
  padj: 0.05