# config.yaml

# === File paths configuration ===
paths:
  base_dir: "datasets"
  scripts_dir: "scripts"

  atacseq_dir: "datasets/ATACseq"
  atacseq_bowtie2_dir: "datasets/ATACseq/bowtie2file"
  rnaseq_dir: "datasets/RNAseq"

  promoter_analysis_dir: "datasets/Promoter_region_analysis"
  enhancer_analysis_dir: "datasets/Enhancer_region_analysis"

  geneanno_dir: "reference"
  geneanno_bed: "reference/geneanno/gencode.v44.annotation.bed"
  enhancer_bed: "reference/enhanno/EnhancerAtlasv2.0_eRNA.bed"

  jaspar_raw: "datasets/JASPAR2024_CORE_vertebrates_non-redundant_pfms_meme.txt"
  jaspar_dir: "datasets/JASPAR2024_CORE"
  tf_mapping_file: "datasets/Homo_sapiens_TF.txt"

# Input files configuration
input_files:
  up_peak_csv: "datasets/ATACseq/macs2file/ATAC_GDC_vs_ATAC_ctr_peak.csv"
  down_peak_csv: "datasets/ATACseq/macs2file/ATAC_ctr_vs_ATAC_GDC_peak.csv"
  
  up_peak_xls: "datasets/ATACseq/macs2file/ATAC_GDC_vs_ATAC_ctr/ATAC_GDC_vs_ATAC_ctr_peaks.xls"
  down_peak_xls: "datasets/ATACseq/macs2file/ATAC_ctr_vs_ATAC_GDC/ATAC_ctr_vs_ATAC_GDC_peaks.xls"
  
  deg_csv: "datasets/RNAseq/stringtiefile/RNA_GDC_vs_RNA_ctr_DEG.csv"

# === Sample information ===
samples:
  SRR28263042:
    group: "ATAC_GDC"
    label: "ATACGDC1"
  SRR28263043:
    group: "ATAC_GDC"
    label: "ATACGDC2"
  SRR28263044:
    group: "ATAC_ctr"
    label: "ATACctr1"
  SRR28263045:
    group: "ATAC_ctr"
    label: "ATACctr2"

# === Analysis parameters ===
params:
  # Differential expression thresholds
  log2fc_up: 0.2
  log2fc_down: -0.2
  padj: 0.05

  # computeMatrix parameters (for promoter and enhancer)
  computematrix:
    before: 1000
    after: 1000
    bin_size: 10
    processors: 10

  # Group analysis settings (for correlation and enhancer analysis)
  group_analysis:
    column_ranges: ["1:200", "201:400", "401:600", "601:800"]
    sample_labels: ["ATACGDC1", "ATACGDC2", "ATACctr1", "ATACctr2"]
    treatment_group: ["ATACGDC1", "ATACGDC2"]
    control_group: ["ATACctr1", "ATACctr2"]

  # enrichment_analysis directories
  enrichment_analysis:
    promoter_up_dir: "datasets/Promoter_region_analysis/Enrichment_analysis/Up"
    promoter_down_dir: "datasets/Promoter_region_analysis/Enrichment_analysis/Down"
    enhancer_up_dir: "datasets/Enhancer_region_analysis/Enrichment_analysis/Up"
    enhancer_down_dir: "datasets/Enhancer_region_analysis/Enrichment_analysis/Down"

  # regulation_analysis directories
  regulation_analysis:
    promoter_up_dir: "datasets/Promoter_region_analysis/Regulation_analysis/Up"
    promoter_down_dir: "datasets/Promoter_region_analysis/Regulation_analysis/Down"
    enhancer_up_dir: "datasets/Enhancer_region_analysis/Regulation_analysis/Up"
    enhancer_down_dir: "datasets/Enhancer_region_analysis/Regulation_analysis/Down"
