# config.yaml

paths:
  base_dir: "datasets"
  scripts_dir: "scripts"
  rnaseq_base_dir: "datasets/RNAseq"
  fastq_dir: "datasets/RNAseq/fastqfile"
  qc_dir: "datasets/RNAseq/quality_control_file"
  hisat2_dir: "datasets/RNAseq/hisat2file"
  stringtie_dir: "datasets/RNAseq/stringtiefile"
  index_dir: "reference/hisat2index"

references:
  gtf_file: "reference/geneanno/gencode.v44.annotation.gtf"
  bed_file: "reference/hg38_GENCODE_V44_Basic.bed"

samples:
  SRR28264346: 
    type: "paired"
    group: "RNA_GDC"
    label: "RNA_GDC1"
  SRR28264347: 
    type: "paired"
    group: "RNA_GDC"
    label: "RNA_GDC2"
  SRR28264348: 
    type: "paired"
    group: "RNA_ctr"
    label: "RNA_ctr1"
  SRR28264349: 
    type: "paired"
    group: "RNA_ctr"
    label: "RNA_ctr2"

params:
  trim_galore:
    phred: 33
    quality: 25
    length_paired: 35
    length_single: 30
    stringency_paired: 3
    stringency_single: 1
  
  hisat2:
    threads: 5
    index_name: "GRCh38"
  
  analysis_groups:
    group_names: ["RNA_GDC", "RNA_ctr"]
    sample_replicates: [2, 2]
  
  deseq2:
    control_group: "RNA_ctr"
    treatment_group: "RNA_GDC"

resources:
  hisat2_threads: 5
  memory_gb: 100

output_dirs:
  hisat2_subdir: "hisat2file"
  stringtie_subdir: "stringtiefile"
